### ISSUE TITLE
[통계] 신규 주문 목록에서 품목을 1개만 주문한 경우 "외 0개"라고 뜹니다.

### ISSUE THREAD

**Issue by yanghyeonjin** [variety-crew/brewnet-app#208]
- 관련 도메인: 통계

## 문제 상황 설명
- 신규 주문 목록에서 품목을 1개만 주문한 경우 "외 0개"라고 뜹니다.

<img width="550" alt="스크린샷 2024-12-03 오전 10 57 46" src="https://github.com/user-attachments/assets/2e1e9e11-65ae-40b4-978c-4a4809fb34dc">

**Comment by JeongJunSeo99** [comment]
![image](https://github.com/user-attachments/assets/6310164e-f646-41ea-bcc4-cd7ad93daf47)

수정 완료입니다
